### ISSUE TITLE
Presences don't update user cache

### ISSUE THREAD

**Issue by VelvetThePanda** [DSharpPlus/DSharpPlus#1041]
# Summary
Presences are a bit borked in the lib. Leave it to me of all people to find out why. :b 

Presence updates for better or worse do not update underlying user objects.

The issue lies on this section of code: https://github.com/DSharpPlus/DSharpPlus/blob/2c74a38c0c39ee7812299a72c6f08cbf74296b20/DSharpPlus/Clients/DiscordClient.Dispatch.cs#L1653-L1684

# Steps to reproduce
- Pick a user that hasn't sent a message (Updates cache)
- Attempt to pull their presence
- Observe null presence, even if they're online

Alternatively:
- Hook PresenceUpdated
- Observe `PresenceBefore` and `PresenceAfter` are not null
- Observe `UserBefore.Presence` is null
- Observe `User.PresenceAfter` is not null

# Notes
<sub>how long has this existed x2</sub>

**Comment by MichailiK** [comment]
This bug seems to be difficult to fix.

https://github.com/DSharpPlus/DSharpPlus/blob/2c74a38c0c39ee7812299a72c6f08cbf74296b20/DSharpPlus/Entities/User/DiscordUser.cs#L178-L184

`DiscordUser`s don't keep a field/local reference of the presence. Instead, they retrieve it from the client's cache.

This should mean that `UserBefore.Presence` should just return the presence from the client's cache, instead of returning null. This isn't the case, because the `Discord` field is not being set (and is thus null)

![rider64_2021-10-02_15-18-16](https://user-images.githubusercontent.com/39029839/135724297-1c2b671b-d911-438c-8837-c7a3aeb3b08f.png)

I'm unable to see any simple way of fixing this, it may require changing `DiscordUser`'s structure. For now, it should perhaps be documented that `UserBefore.Presence` will return null, and that `PresenceBefore` should be used instead.

**Comment by VelvetThePanda** [comment]
Should be fixed in theory? See 23e7a8db, and I'll reopen if this issue persists.
