### ISSUE TITLE
VoiceReceived event stops getting raised after a while because the packet sequence number overflows

### ISSUE THREAD

**Issue by NDobricic** [DSharpPlus/DSharpPlus#1084]
# Summary
After a while (anywhere from 5 to 30 minutes), the `VoiceReceieved` event in `VoiceNextConnection` stops getting raised for a particular user.

# Details
I'm making a bot that relies on constantly listening to everyone in the current channel for a prolonged amount of time. I'm doing this using the `VoiceReceived` event from `VoiceNextConnection`. The event stops getting raised for a particular user after a seemingly random amount of time.

# Steps to reproduce
1. Subscribe to the `VoiceReceived` event
2. Log a message every time the event gets raised
3. Connect to a channel
4. Find something to provide a constant supply of audio in the Discord channel (I used the Pancake bot and played some music on it)
5. Leave the program running
6. The event will stop getting raised after a while even though there is still incoming audio

# Notes
As it turns out, the time after which the event stops working isn't random at all. I've traced back the issue to this particular line:
https://github.com/DSharpPlus/DSharpPlus/blob/62ed90432b52a58d5a33d020ec7b19a981b3a93d/DSharpPlus.VoiceNext/VoiceNextConnection.cs#L475-L476

This is meant to discard packets that are in the wrong order, but the problem arises when the sequence number overflows (which is not that hard since it's a `ushort`). `vtx.LastSequence` stays at the maximum `ushort` value for the remainder of the session and all following packets get discarded since `sequence` is always less than `vtx.LastSequence`.

The logical solution would be to just change the type to `uint` instead, but I know very little about both audio processing and sending data over the internet so I don't know how practical this is, if possible at all.

EDIT: some grammatical errors

**Comment by Emzi0767** [comment]
It is not possible because ushort reflects the data in the packet.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: NDobricic ***@***.***>
Sent: Saturday, September 18, 2021 12:36:16 PM
To: DSharpPlus/DSharpPlus ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [DSharpPlus/DSharpPlus] VoiceReceived event stops getting raised after a while because the packet sequence number overflows (#1084)


Summary

After a while (anywhere from 5 to 30 minutes), the VoiceReceieved event in VoiceNextConnection stops getting for a particular user.

Details

I'm making a bot that relies on constantly listening to everyone in the current channel for a prolonged amount of time. I'm doing this using the VoiceReceived event from VoiceNextConnection. The event stops getting raised for a particular user after a seemingly random amount of time.

Steps to reproduce

  1.  Subscribe to the VoiceReceived event
  2.  Log a message every time the event gets raised
  3.  Connect to a channel
  4.  Find something to provide a constant supply of audio in the Discord channel (I used the Pancake bot and played some music on it)
  5.  Leave the program running
  6.  The event will stop getting raised after a while even though there is still incoming audio

Notes

As it turns out, the time after the event stops working isn't random at all. I've traced back the issue to this particular line:
https://github.com/DSharpPlus/DSharpPlus/blob/62ed90432b52a58d5a33d020ec7b19a981b3a93d/DSharpPlus.VoiceNext/VoiceNextConnection.cs#L475-L476

This is meant to discard packets that are in the wrong order, but the problem arises when the sequence number overflows (which is not that hard since it's a ushort). vtx.LastSequence stays at the maximum ushort value for the remainder of the session and all following packets get discarded since sequence is always less than vtx.LastSequence.

The logical solution would be to just change the type to uint instead, but I know very little about both audio processing and sending data over the internet so I don't know how practical this is, if possible at all.

**Comment by airbreather** [comment]
I'm not an expert in audio or network protocols, and I don't currently have the opportunity to try this out myself, but would it perhaps be viable to change `AudioSender.LastSequence` to an `int` (the value doesn't go on the wire), and then modify the linked section with something that detects overflow heuristically?
```csharp
if (vtx.LastSequence - sequence > short.MaxValue)
{
    // either we missed a HECKING lot of packets and we're JUST NOW catching up,
    // ...or else the sequence number just overflowed.  let's assume the latter.
    vtx.LastSequence -= ushort.MaxValue;
}

if (sequence <= vtx.LastSequence) // out-of-order packet; discard
    return false;
```

**Comment by airbreather** [comment]
Searching around, it looks like the RTP spec actually does suggest how to deal with wraparound, see [RFC 3550 A.1](https://datatracker.ietf.org/doc/html/rfc3550#appendix-A.1) (as part of a larger routine, `update_seq`, which also does some more stuff that might be a bit overkill for a Discord client, but :man_shrugging:).

**Comment by OoLunar** [comment]
Thank you for linking me, I'll be sure to reference it when making the VNext rewrite
