### ISSUE TITLE
Add support for sharding in multiple-process in SlashCommands extension

### ISSUE THREAD

**Issue by bakabun** [DSharpPlus/DSharpPlus#1155]
# Summary
Apparently SlashCommands extension doesn't support sharding in multiple-process yet.

# Details
Slash command will throw `InvalidOperationException` with message "A slash command was executed, but no command was registered for it." when executed on shard that doesn't share process with shard 0. Idk if it's possible or not to implement something like this.

Example visualization
```
process 0
|- shard 0  // slash works here
\- shard 1  // slash works here
process 1
|- shard 2  // slash doesn't work here
\- shard 3  // slash doesn't work here
``` 

# Steps to reproduce
1. Make a bot with global slash command.
2. Run 2 processes of bot, each process handles its own shard (shard 0, and shard 1)
3. Execute global slash command in shard 1.
4. `InvalidOperationException` with message "A slash command was executed, but no command was registered for it." thrown on shard 1.

# Notes
English is not my native so I'm sorry if it's confusing.

**Comment by VelvetThePanda** [comment]
If you have two bots, and you're not setting the ShardId manually (which is required for proper sharding anyway), then this is technically intentional behavior. The slash command extension inherently has no concept of multi-process sharding, because the library doesn't really have the concept of proper multi-process sharding.

You will either have to set the shard Id (slash commands are only registered on shard 0), or add a check to see if this is your main cluster, and ensure that you're on the correct shard.

--------

Though, as of writing this, I did realize that there's a bigger issue, and it cannot be solved easily. The slash command extension relies on a local cache for slash commands.

Given that this cache is only populated at startup, attempting to pull that state from Discord for every client, and hack your way around cache would result in plenty of 429s.

**Comment by bakabun** [comment]
What was I think is the to workaround this is **a method to manually pull the list of already-registered commands from discord then register them against the current methods and classes** (honestly idk how slash extension handles it).

So it will be possible to do something like this:
```
if (shard == 0) => // register commands to discord as usual
else if (shard == first_shard_in_cluster) => // pull already registered commands to use
```
```
process 0
|- shard 0  -> register commands to discord
\- shard 1  
process 1
|- shard 2  -> pull registered commands from discord then use it for all shards in this process
\- shard 3  
```
The limitations is that the process that contains shard 0 must be started first and the check for first shard in cluster should be done manually by bot dev since it's outside the scope of library.

About ratelimit concerns, sadly I can't find reference about it since endpoint for both `GetGlobalApplicationCommands` and `GetGuildApplicationCommands` don't have ratelimit information in its header so I can assume it will follow global ratelimit instead.

**Comment by VelvetThePanda** [comment]
> a method to manually pull the list of already-registered commands from discord

This already exists in the client, but as I mentioned before you can and probably will receive a 429 faster than you can say “oh no I got ratelimited”. 

I’m not sure, but last I checked Discord doesn’t specify anything regarding slash commands and sharding, so slash commands via gateway may not even be ideal for “clustered” bots; either the gateway will send it only to the first shard, or it will send it to all shards. The issue with the latter is you could vary easily get api blocked by CF for hitting too many 404s because a different shard already responded. My bet is on the first one, though, since slash commands are only registered on the first shard (granted, D#+ doesn’t have proper sharding, and [my PR to fix this](https://github.com/DSharpPlus/DSharpPlus/pull/958) was declined. 

Overall I think you should either only worry about slash commands in your first shard, or simply use HTTP interactions, which are not only faster*, but you also get the cool status indicator remover. On top of that, you don’t have to worry about sharding, since the payload is sent to a single endpoint, which can be proxied to any shard via a load balancer.

**Comment by bakabun** [comment]
> either the gateway will send it only to the first shard, or it will send it to all shards.
From what I tested so far, gateway send the event for executed slash command on shard where the guild belongs to (or shard 0 if DM). That's why "A slash command was executed, but no command was registered for it." error fired when slash command executed in shard which run on different process with shard 0. That error won't be fired if event from all shards sent to shard 0 or sent to all shards. (Yeah, discord really unclear about this behavior)

**Comment by IDoEverything** [comment]
This sounds very challenging to implement. Currently, the extension works for the `DiscordShardedClient` by registering commands only for the shard with id 0, then it saves everything to a static list so it can be accessed by any shard. Repurposing this for something that works in separate processes seems impossible. 

It would probably have to be as you suggested, by pulling the current list of commands and checking them against those already registered. This is actually something that's been requested before, but mostly for preventing the update of slash commands every time you restart your bot. Implementing that seems like it would be extremely tedious, which is why I've been reluctant to even try before.

You probably shouldn't expect any work on this on my part in the forseeable future, though if anyone is willing to help out then I might consider it. For now, you can try using a custom implementation that doesn't depend on reflection as horribly as it does in the extension. If you do decide to go that route, you can expect assistance in the dsharpplus server if you need it.

**Comment by VelvetThePanda** [comment]
As I commented before, there’s two much larger issues here. 

1: D#+’s sharded client is not intended for multi-process sharding (see my previous comment)
2: While gateway interactions occur on their respective shard, if you’re doing multi-process sharding HTTP interactions would scale far better, but require some more setup.

**Comment by VelvetThePanda** [comment]
@bakabun technically speaking, it would be a little inefficient, but now that updating slash commands is an idempotent endpoint, you could call `RefreshCommands`, which will internally map (and attempt to register) slash commands and contextt menus, and in theory it won't break other shards. 

It's all just a theory, because you know, Discord, but it's worth a shot! Let me know how it goes :)
