### ISSUE TITLE
Support for Pagination within Slash Command Responses

### ISSUE THREAD

**Issue by SeraphimRP** [DSharpPlus/DSharpPlus#1162]
Hello.

Title basically explains it. As it stands, the way this has to be handled typically regards a more manual sense, with either doing all the interactivity by hand or by doing something with `ctx.Client.GetInteractivity().SendPaginatedResponseAsync()` (albeit this creates a 404 error for me).

It's possible this is a bug on my end, but regardless, having InteractionContext provide a seamless helper for these would be greatly preferred.

**Comment by ProfDoof** [comment]
So, this is just me taking a gander at it. But if this was to be a thing,
1. It wouldn't be something that we put on the `InteractionContext`. `InteractionContext` and `InteractivityExtension` belong to two separate packages. Might could be an extension method though and that would functionally do the same thing. 
2. While this might be convenient as it is something that people commonly do, it's another thing that we have to evaluate when we do the rewrite eventually:tm: . 

Aside: For help with the 404 you are having, I would suggest going to the support server - https://discord.gg/dsharpplus

**Comment by IDoEverything** [comment]
This is already supported with the `SendPaginatedResponseAsync` method. It won't be added directly on the `InteractionContext` since that would add a dependency, but you can still use it with `context.Interaction.SendPaginatedResponseAsync`. If you're getting a 404, that's either because you haven't initialized interactivity on the client, or you're trying to create a second response or you're past the 3 second limit. If you want pagination when editing the response, there's already an open pull request for that #1156
