### ISSUE TITLE
User.Username is Null after first VoiceStateUpdated event

### ISSUE THREAD

**Issue by shnytzl9000** [DSharpPlus/DSharpPlus#1168]
# Summary
User.Username is Null when the VoiceStateUpdated event triggers for the first time.

# Details
I am porting my bot currently from DSharp+ 3.2.3 to 4.1.0. I implemented a logging function, which basically just sends a message to a specific channel when a user joins, switches of leaves a voice channels, in the form of "09:48: User joined channel Games" etc.

In version 3, when doing 
```
discord.VoiceStateUpdated += async v => 
{
v.User.Username.ToString();
}
```

User.Username is populated with the actual username, even when the user joins from being in no voice channel to a voice channel. In version 4, when doing

```
discord.VoiceStateUpdated += async (f,v) => 
{
v.User.Username;
}
```

Username is Null, even though v.User.Id has the correct Id. After the User joins another channel or leaves, everything is working as expected, User.Username is not Null and contains the username.

# Steps to reproduce
1. Wait for VoiceStateUpdated trigger
2. Inspect User.Username when a user joins a voicechannel from being online and without being in another voicechannel first

If this is a bug in the current version, is there a workaround? Otherwise I cannot port from version 3 to 4 as this is an essential function for the bot. 

Thanks,
Marc

**Comment by VelvetThePanda** [comment]
Currently following up with some others to see if this was a change in behavior, though I believe @alexhorner has reported a similar issue in the past, so this may purely be a caching issue

**Comment by VelvetThePanda** [comment]
Putting this on hold until the cause of the issue can be identified. Thanks!

**Comment by OoLunar** [comment]
Unable to duplicate with the following code:
```cs
using System.Threading.Tasks;
using DSharpPlus;
using DSharpPlus.EventArgs;

namespace Tomoe.Commands
{
    public partial class Test
    {
        public static async Task VoiceStateUpdate(DiscordClient discordClient, VoiceStateUpdateEventArgs voiceStateUpdateEventArgs) => await discordClient.Guilds[832354798153236510].GetChannel(832362208209010721).SendMessageAsync($"{voiceStateUpdateEventArgs.User.Username} ({voiceStateUpdateEventArgs.User.Id}) has updated.");
    }
}
```
It should be noted that you'll need to register the event on the `DiscordClient` and pass the `DiscordIntents.GuildVoiceStates` intent through a `DiscordConfiguration` (which will need to be passed as a parameter when constructing your `DiscordClient`.

![image](https://user-images.githubusercontent.com/46751150/147863734-915b3870-357b-4e74-a4ec-34120581ec5c.png)
The events above showcase me doing the following actions:

- Self (un)muting
- Self (un)deafening
- Server (un)muting
- Server (un)deafening
- Switching between a voice channel to a stage channel
- Becoming a speaker
- Starting an event
- Self (un)muting
- Moving to the audience
- Exiting quietly

Not all events will match up since I did a few more after the screenshot was taken, however I cannot reproduce. If you still happen to have your code, could you please test if the behavior still happens for you on the [latest nighty](https://nuget.emzi0767.com/gallery/package/DSharpPlus/4.2.0-nightly-01055) (you may need to edit your nuget sources) and if it does, could you please send a minimal repro?

Thank you @shnytzl9000

**Comment by shnytzl9000** [comment]
Hello @OoLunar,
I did indeed not register the event during instantiation, after doing so everything works as expected again. 
Thank you for your help!

Marc
