### ISSUE TITLE
ActiveConnections in VoiceNext are not updating resulting in Null Returns

### ISSUE THREAD

**Issue by MelodicAlbuild** [DSharpPlus/DSharpPlus#1187]
# Summary
`ActiveConnections` in `DSharpPlus.VoiceNext.VoiceNextExtension` is never updated which means that any GetConnection calls return null instead of the active connection that might be made.

# Details
- .NET 5.0
- Windows 10 | Ubuntu 20.04
- DSharpPlus 4.2.0-nightly-01057
- DSharpPlus.VoiceNext 4.2.0-nightly-01057

# Steps to reproduce
1. Setup a Sample VoiceNext client and CommandsNext client.
2. Create a command that joins a channel and then sends the VoiceNextExtension.GetConnection(DiscordGuild guild) function's return.
3. See the null response to no response at all based on implementation.

# Notes
There is really no good workaround for this right now. I am working on a simple fix, I will PR it if I am able to find a solution.

**Comment by MelodicAlbuild** [comment]
In searching further down the pipeline *and looking up many many things you all have done for VoiceNext* I found that the `vnc` variable that you all set in `VoiceNextExtension.cs` on line 130, is nulled out after line 133, I'm not sure why but both the return and `this.ActiveConnections[gld.Id] = vnc;` are sending null, which means the ActiveConnections lookup done in GetConnection will find a guild, but return a null object for the Connection. I'm not sure why it's nulling out yet but I'll do some more digging.

**Comment by MelodicAlbuild** [comment]
Now I have even more interesting information, after polling my resources, I got it to work about 50% of the time when I'm running it in debug on my PC. However the moment I run it in release on my linux server, it doesn't throw exceptions, but it also doesn't work at all. It ends up freezing the bot completely. No commands run, no events fire, my guess is that the `ConnectAsync` function get's stuck, I can't figure out where yet, but I'll see what I can find.

**Comment by OoLunar** [comment]
https://github.com/DSharpPlus/DSharpPlus/blob/bd5bfb30d2cb03b23223207993f90f8e043be127/DSharpPlus.VoiceNext/VoiceNextExtension.cs#L133

This line never returns, which results in `this.ActiveConnections[gld.Id] = vnc;` never being sent, or `vnc` never being returned.

**Comment by OoLunar** [comment]
https://github.com/DSharpPlus/DSharpPlus/blob/bd5bfb30d2cb03b23223207993f90f8e043be127/DSharpPlus.VoiceNext/VoiceNextExtension.cs#L133

https://github.com/DSharpPlus/DSharpPlus/blob/43c717f4946edb364bf571438437ec0e0eef2154/DSharpPlus.VoiceNext/VoiceNextConnection.cs#L869

https://github.com/DSharpPlus/DSharpPlus/blob/43c717f4946edb364bf571438437ec0e0eef2154/DSharpPlus.VoiceNext/VoiceNextConnection.cs#L891

The reason why it never returns is because the task that the Stage2 method is never called. The Stage2 method is for the session description, [op code 4](https://discord.com/developers/docs/topics/opcodes-and-status-codes#voice-voice-opcodes), to be sent. Now what we need to debug is why this method isn't being sent, or why the `HandleDispatch` method isn't being called

**Comment by OoLunar** [comment]
After installing **both** libsodium and libopus, as per https://dsharpplus.github.io/articles/audio/voicenext/prerequisites.html#linux, and switching the following line in your example from
```cs
if (!member.Guild.Roles.ContainsKey(staffRole)) // This checks if the staff role exists
```
To
```cs
if (!member.Roles.Where(role => role.Id == staffRole).Any()) // This checks to see if the user has the staff role
```
Your example works as expected. Make sure you have the following library installed on both Windows and Ubuntu. On Windows, this shouldn't be a problem since the `DSharpPlus.VoiceNext.Natives` package is automatically installed, which comes with libsodium and opus. On Linux, I installed the `libsodium-devel` and `libopusenc-devel` packages for the Void Linux distribution (package names will likely vary per distro)

**Comment by OoLunar** [comment]
Due to inactivity I'm going to close this issue and assume it's solved. If this is not the case, feel free to let us know and we can reopen the issue
