### ISSUE TITLE
DiscordMember.Presence is inconsistently null

### ISSUE THREAD

**Issue by OneYellowLemon** [DSharpPlus/DSharpPlus#1275]
# Summary
`DiscordMember.Presence` may be null when you're invisible.

# Details
`DiscordMember.Presence` may be null if you're invisible. This only happens if you start your bot while being offline and do not change your status. Once you change it to something else and back to invisible, `DiscordMember.Presence` will no longer be null and `DiscordMember.Presence.Status` will correctly reflect a `UserStatus.Offline`.

I was able to reproduce this when clicking a button that would print my status.

# Steps to reproduce
1. Make a button that logs `DiscordMember.Presence` when clicked
2. Go invisible on Discord
3. Start your bot
4. While invisible, click the button. `DiscordMember.Presence` will be null.
5. Change your status to online and back to invisible on Discord.
6. Click the button again. `DiscordMember.Presence` will be no longer be null and you can properly see `DiscordMember.Presence.Status == UserStatus.Offline`.

DSharpPlus `4.2.0-nightly-01111`

**Comment by VelvetThePanda** [comment]
I can't *really* say this is a bug? This is simply how Discord functions, technically speaking. As per the [docs](https://discord.com/developers/docs/topics/gateway-events#identify-identify-structure) if a guild is large (members __>__ `large_threshold`), offline members are not sent in the corresponding `GUILD_CREATE` payload. We can't polyfill their presence with `UserStatus.Offline` either because if the presence intent isn't enabled, the cache would be full of invalid data, which isn't good. If you need to know the status of all users on a server, consider using `DiscordGuild#RequestMembersAsync`

**Comment by OoLunar** [comment]
> We can't polyfill their presence with `UserStatus.Offline` either because if the presence intent isn't enabled, the cache would be full of invalid data, which isn't good. 

Could we conditionally fill it if the user has requested the presence intent? Maybe add a `<remark>` on the property about it?

**Comment by VelvetThePanda** [comment]
I'll reiterate
> the cache would be full of invalid data, which isn't good.

**Comment by VelvetThePanda** [comment]
If we were to fill it, no matter the condition, there's no guarantee that the data about that user is correct (they could be online, for example)

**Comment by VelvetThePanda** [comment]
And we shouldn't make behind-the-scenes API calls, otherwise we'll turn into DCS.
