### ISSUE TITLE
Members & Users & Casting

### ISSUE THREAD

**Issue by Liviu50** [DSharpPlus/DSharpPlus#1291]
So this might be something either intended or how discord works but i wish to make sure of it.
So i was trying to take care of some direct message stuff and i had a simple way i found to do it...except for one little issue.
I tried to get the user in the hope i could use it as a member like the following:

var user = await ctx.Client.GetUserAsync(player.discord_ID);
Now...the reason i did this is because i also had another function doing something like the following:
await ((DiscordMember)ctx.User).SendMessageAsync("test");
And this worked but only with the user using the command.
Now...as you can see GetUserAsync and ctx.User SHOULD be both users...
but if i try to do the following:
await ((DiscordMember)user).SendMessageAsync("test");
it gives an error but using the ctx.User did not.
Now, this would not be the worst things but i could literally send dm with 2 lines of code instead of using other ways that might be longer or require extra things to make them work.
Some extra info:
.NET 6
DSharpPlus latest nightly
Windows 10

If this could be solved or if you could use the one that gives error it would make a lot of things easier but i do not know how much this is doable or impossible depending on Discord so i hope this ticket would give some info or even a solution.
Cheers!

**Comment by ExaInsanity** [comment]
this is unfortunately not really possible. `DiscordUser` can only be casted to a `DiscordMember` if it originally was a `DiscordMember`, which is the case for `ctx.User` (and even then only if the command was executed in a guild), but not for `DiscordClient.GetUserAsync`

**Comment by ExaInsanity** [comment]
For sending direct messages, if you don't want to deal with getting the guild member object but know you share a guild with the user, you can always use `DiscordRestClient.CreateDmAsync` (from DSharpPlus.Rest) to get a DM channel.

**Comment by OoLunar** [comment]
While there is absolutely nothing wrong with Exal's response, I would like to add some clarification:
1. `DiscordMember` inherits from `DiscordUser` (as in, `public sealed class DiscordMember : DiscordUser`). This means that `DiscordMember` can be casted to `DiscordUser`, however `DiscordUser` can only be casted to `DiscordMember` if that object is already a `DiscordMember`. We do this since, on certain payloads, such as `MessageCreate`, most of the mentioned users on `DiscordMessage.Mentions` are actually `DiscordMember`s even though the list shows `IReadOnlyList<DiscordUser>`. This is because a mention is just formatted id's (`<@336733686529654798>`) that anyone can send, but it's up to Discord to test if any of those ids are in the guild. See [the `MESSAGE_CREATE` gateway payload](https://discord.com/developers/docs/topics/gateway#message-create) for more information.
2. Even if we *did*  want to allow casting a `DiscordUser` instance to `DiscordMember`, we'd first have to obtain a `DiscordMember` in some way (I.E, hidden API requests or cache). Hidden API requests are a huge no-go, though there are times when we have to do so (such as the `DiscordMember.SendMessageAsync` method). Grabbing the DiscordMember from the cache would require a massive memory footprint since we'd have to store an instance of `DiscordMember` per `DiscordUser` (though, I guess this could be partially mitigated by casting the `DiscordMember` to `DiscordUser`).
3. The biggest issue: A `DiscordUser` can be in multiple guilds. While this doesn't matter for sending DM's, I'm certain new users would think they could grab roles or other per-guild properties and not realize that they could be grabbing the properties from an entirely contextually incorrect guild.

Point number 1 explains why `DiscordUser` can be conditionally casted to `DiscordMember`: Did Discord send a `DiscordMember` or `DiscordUser`? If it sent a `DiscordMember`, we can save an API request and update the outdated cache by casting the `DiscordMember` to a `DiscordUser`.

Just as a final comment: I'm not mad, and I apologize if I man-splained it. While the convenience of casting a `DiscordUser` to a `DiscordMember` would be nice, as lib maintainers we have to make sure the use is correct. That's why we have it as it currently is.

**Comment by Liviu50** [comment]
Oh absolutely nothing to apologize for :).
I found this possible solution while i spent an entire day on the matter to make my code shorter and more efficient and i saw those two...and well i was simply perplex. So i thought to ask the experts. 
I do appreciate all the explanation and guidance you gave me and thank you very much for showing the why and how this wont work in the way i thought about it.
Appreciate all the effort everyone! :)
