### ISSUE TITLE
SlashCooldown incorrectly failing cooldown check when used inside a SlashCommandGroup

### ISSUE THREAD

**Issue by JackSteel97** [DSharpPlus/DSharpPlus#1419]
# Summary
Applying `SlashCooldown` attributes to methods inside a command group I'd expect the same behaviour as the regular commands `Cooldown` attribute - the cooldown applies to that specific command in the group. i.e. with `[SlashCooldown(5, 60, SlashCooldownBucketType.User)]` applied to method `Bar` in Group `Foo` I'd expect to be able to execute `/Foo Bar` 5 times in 60 seconds and then execute `/Foo Buzz` without issue in the same 60 second period.

# Details
The below minimal example has been tested on `4.3.0-nightly-01189` on a Windows 10 system running in debug mode, with the Guild Id specified when registering the slash commands

```cs
[SlashCommandGroup("Example", "Testing")]
public class MinimalExampleSlashCommands : ApplicationCommandModule
{
    public MinimalExampleSlashCommands()
    {
    }

    [SlashCommand("Example1", "Test 1")]
    [SlashCooldown(5, 60, SlashCooldownBucketType.User)]
    public async Task Example1(InteractionContext context)
    {
        await context.CreateResponseAsync(InteractionResponseType.DeferredChannelMessageWithSource);
    }
    
    [SlashCommand("Example2", "Test 2")]
    [SlashCooldown(5, 60, SlashCooldownBucketType.User)]
    public async Task Example2(InteractionContext context)
    {
        await context.CreateResponseAsync(InteractionResponseType.DeferredChannelMessageWithSource);
    }
}
```

# Steps to reproduce
1. Add the above code to your project
2. Register `MinimalExampleSlashCommands` with the SlashCommands for the bot
3. Run the application
4. Execute `/Example Example1` 5 times within 60 seconds
5. Then Execute `/Example Example2` immediately after
    a. **Expected**: The `Example Example2` command runs fine
    b. **Actual**: The command throws a `SlashExecutionChecksFailedException` with a failed check for the `SlashCooldownAttribute`

![image](https://user-images.githubusercontent.com/13905557/205386530-2606783b-a5f7-49b9-98e1-8e1f024f97bc.png)

**Comment by VelvetThePanda** [comment]
@OoLunar so, here's an interesting thing.

Cooldowns *should* be static (at least, their dictionary) since attributes are re-init'd when you grab them via reflection (which partially explains why Remora separates these concerns for conditions)

You can technically use `[CallerMemberName]`, but that quickly falls apart. Given that this is an issue, I believe the CNext version may also be plagued with this issue, but nobody's just ever reported it.

![image](https://user-images.githubusercontent.com/42438262/205785773-8d3f6ac5-71ab-43b5-99fc-3694a92c23ce.png)

**Comment by JackSteel97** [comment]
I can confirm CNext does not suffer from this bug at least in my specific setup. I noticed this because I was writing slash command versions of a CNext command group that makes use of the cooldowns as a feature and got this unexpected behaviour with only the slash command version

**Comment by VelvetThePanda** [comment]
As it turns out this issue is actually architectural; D#+ (the core library) holds a cache of command metadata, including attributes, which the slash command library doesn't (something I'm currently unintentionally [fixing elsewhere](https://github.com/Remora/Remora.Commands/pull/20). 

cc @IDoEverything @OoLunar it would be quite the investment, perhaps more apt for V5 since Aki said she wanted a unified command library anyways, but if we were to port CNext's common infrastructure (command  metadata, builders), we could somewhat trivially solve this issue.

**Comment by OoLunar** [comment]
> cc @ IDoEverything @OoLunar it would be quite the investment, perhaps more apt for V5 since Aki said she wanted a unified command library anyways, but if we were to port CNext's common infrastructure (command metadata, builders), we could somewhat trivially solve this issue.

If I were to have influence in the unified command library, I'd certainly like to use my [extension](https://github.com/OoLunar/DSharpPlus.CommandAll/) as influence for the base. 

If, I were to continue development on v5. Before that, there are much more important things that I must do irl first. Regardless, discussion for that isn't fit here.
