### ISSUE TITLE
Add Shard ID to event args.

### ISSUE THREAD

**Issue by ecrocombe** [DSharpPlus/DSharpPlus#2027]
### Description

Prior to the new Sharding System, The DiscordClient (sender) in the event handlers used to contain the Shard ID. 

Now since the DiscordClient is a sharded client by default, the sharding info is absent.

Is it possible to add the shard specific info to the event args instead?

### Specify the libraries you want this feature request to affect

DSharpPlus, the core library

**Comment by ecrocombe** [comment]
Well, it probably would suffice in most cases, however in the likes of 
- SessionCreated
- SocketOpened
- Zombied

There is no Guild ID either

**Comment by akiraveliara** [comment]
those we can add connection information to, that's no problem

**Comment by Naamloos** [comment]
There's irony here where nowadays I'd say "that data doesn't belong in events because it's not sent by Discord" but DSharpPlus by design (at least when I originally worked on it up to ~v3/v4) does some more hand holding than the average Discord library

However, I do think it's valueable to at least give this info to a user in some way since we have a sharded client that throttles down multiple shard's events down one "event" from what I have seen
