### ISSUE TITLE
Messages are spammed if on a server but not on a dev machine.

### ISSUE THREAD

**Issue by EoinAviation** [DSharpPlus/DSharpPlus#294]
# Summary
When our bot is deployed on a server, it behaves in a very different way.
It will continually spam messages when it should only be sending one.
For example, when testing on my local development environment (Expected Behaviour):
![Expected Behaviour](https://image.prntscr.com/image/07WvivURT0aBWXceVnOwwQ.png)

However, when on the server (Actual Behaviour):
![Actual Behaviour](https://image.prntscr.com/image/Y1yhlxsrSFmWRD6J7k-_Yw.png)

No exceptions are thrown in relation to this error. However, when we do have an expected error (Which we have forced for testing purposes), that error will be continually thrown until the bot is kicked from the Discord Server, or the IIS server is shut down:
![Spam](https://image.prntscr.com/image/v9MHbfcmTmSNHETLTOknKA.png)

# Details
The server running Windows 2016 Server with IIS, WebDeploy and SQLExpress.
The bot is being run through an ASP.NET MVC5 instance.
The application is deployed to the server using Visual Studio 2017s built in WebDeploy publishing.

For reference, our ping method is:
```CS
[Command("ping")]
[Description("Example ping command")]
[Aliases("pong")]
public async Task Ping(CommandContext ctx)
{
	await ctx.TriggerTypingAsync();

	var emoji = DiscordEmoji.FromName(ctx.Client, ":ping_pong:");

	await ctx.RespondAsync($"{emoji} Pong! Ping: {ctx.Client.Ping}ms");
}
```

# Steps to reproduce
1. Deploy the application to a Windows 2016 Server from Visual Studio 2017 using WebDeploy.
2. Invoke a method that will result in the bot sending a message to the server (Eg: `ctx.RespondAsync()` or `SendMessageAsync()`).

# Notes
This issue does not occur on our local machines, it only happens once it's running on our server.
I apologise if I have not provided sufficient information. Feel free to ask for any more information!

**Comment by Emzi0767** [comment]
Are you sure that:

1. It's running on a single instance only? Try adding some diagnostic info to the output (e.g. machine name).
2. You aren't accidentally hooking some events several times? Try checking for all references to `MessageReceived` event.
3. Your bot doesn't get stuck in some weird loop where it keeps on connecting, thus spawning new instances? Does the message count increase as the time passes?

**Comment by EoinAviation** [comment]
Hi @Emzi0767 

1. There is only one instance of the application running.
2. That snippet of code is the only bot related code (other than some startup and config stuff to get it working on our server)
3. No loops.

I have since resolved the issue!

I had to **disable the HTTP proxy in my Cloudflare DNS settings**.

**Comment by uwx** [comment]
Is something like "Maximum Worker processes" in IIS set to more than 1? This seems to be a very clear case of instance duplication, which could be caused by some automated parallelization system you're using. Can you include some data like `Thread.CurrentThread.Name` or `Thread.CurrentThread.ManagedThreadId` in your pong messages?

**Comment by EoinAviation** [comment]
Just an update.
![Threads](https://image.prntscr.com/image/lgo-gXEkTKCu27Nqu6cN5g.png)

Only happens on a server.
All on the one thread when on a dev machine.
What would be your advice moving forward?

**Comment by uwx** [comment]
Are you using sharding? Seems like either ASP or IIS is messing something up. The hacky, easy solution would be to create a lockfile on client connect, and then never connect again if that file is present. I have no experience with either platform, so without actually reading your code and taking some wild guesses I can't be sure what solution will work or not. If this workaround fails, try making a fork process that you run your bot on, with the same lockfile system to stop it from being spawned more than once; if it works, it's time to figure out why your server is making more than one client.

**Comment by EoinAviation** [comment]
The lockfile you mention won't work.
The bot isn't making multiple connections. About 10 mins later, it went back to normal and only spat out one message as it should.
It's as though the `public async Task` methods are being threaded automatically.

**Comment by Emzi0767** [comment]
Theoretically they create a state machine, but so long as they are the entry point, it doesn't even matter. This just looks like something spins up multiple instances of your bot. Thread ID being different for each response is not abnormal - commands are handled on separate threads so as not to block the client event loop - but PID would suggest this is indeed not a worker issue. 

I can't say I know what's going on, I've never embedded a bot in an ASP.NET application before. Is your bot started with the application? In that case it might be the fact that the applications on IIS are shut down after a while in order to conserve resources, and your bot is possibly not being shut down when the app is. The applications are then brought back up on first request to the appropriate application - the bot might be started again here, which would cause the duplication, you now have an additional instance of the bot running. As far as I know, IIS recycles worker processes (or maybe even uses a single one - that might explain the PID). You said on a dev machine this works fine. I imagine you're debugging either standalone app or IIS Express, neither of which would exhibit this behaviour.

I'd try to investigate in this direction. Check your application pool settings, specifically the ones responsible for terminating idle applications.

**Comment by Emzi0767** [comment]
There's no further activity here. If you happen to encounter any additional issues feel free to reopen this issue.
