### ISSUE TITLE
Create DM Channel for DiscordUser

### ISSUE THREAD

**Issue by 13xforever** [DSharpPlus/DSharpPlus#309]
On current nightly build (4.0.0-beta-00467) you can only create DM channel for a `DiscordMember` entity, but not for a `DiscordUser`, which is a bit head scratching.
Also of note is that you can't cast or convert `DiscordUser` to `DiscordMember`, which is also kinda strange and not obvious why that is so.

I am using .net core 2.1, but looking at the code, it doesn't matter.

I propose to add the missing `.CreateDmChannelAsync()` method to the base class, and return the missing similar method/extension for `DiscordClient` which receives `DiscordUser` or even just user id.

**Comment by Emzi0767** [comment]
It's not head-scratching. You can only DM people whom you share servers with, or are friends with, and who have DMs enabled. As bots cannot have friends, you can only DM people who share servers with the bot, and who allow DMs from server members. Thus, you require a `DiscordMember` object.

Which brings me to the second point. `DiscordMember` is a `DiscordUser`, but not the other way around. A member belongs to a guild (server), whereas user is just a user, not affiliated with any users.

This is all by design and Discord-compliant. If you want to DM a member, you need to query your guilds for a member with matching ID, and go from there.
