### ISSUE TITLE
DiscordChannels.DeleteAsync() :  NotFoundException 

### ISSUE THREAD

**Issue by Elyspio** [DSharpPlus/DSharpPlus#349]
# Summary
We want to delete all channels from a Guild and it throws a 'NotFoundException'.
# Details
We tried it on public version (Nuget) and on Beta (MyGet).

this is the stack trace: 
 `
DSharpPlus.Exceptions.NotFoundException: Not found: 404
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at WereWolfRebirth.BotCommands.<CreateGuild>d__1.MoveNext() in P:\PERSO\DiscordBot\WerewolfRebirth\BotCommands.cs:line 148
`

**Comment by Kiritsu** [comment]
Any more information? (code)

**Comment by Elyspio** [comment]
woops : 
`
     foreach (DiscordChannel discordChannel in e.Guild.Channels)
            {
                await discordChannel.DeleteAsync();
            }
`cs

**Comment by WamWooWam** [comment]
Not even `DiscordGuild#DeleteAllChannelsAsync` smh

**Comment by uwx** [comment]
NotFoundException has a `JsonMessage` property, please try-catch it and say what the message is. If I had to take a wild guess it's possibly a design inconsistency in the API and you're trying to delete channels you can't see, so it gives you a 404 instead of a 403, but that's misleading since Discord gives you basic information even for channels you can't see.

**Comment by Elyspio** [comment]
I got "Unknown Channel", and now what can I do ?
