### ISSUE TITLE
ability to handle type errors and other checks with appropriate messages in commandsnext

### ISSUE THREAD

**Issue by ellisonch** [DSharpPlus/DSharpPlus#356]
This is related to the commandsnext module.

I would like my bot to return an appropriate error message to the user when checks fail, such as wrong argument types, Cooldowns, etc.

For example:
```cs
[Command("foo")]
public async Task Foo(CommandContext ctx, int bar) 
```

If a user says  `!foo someString`, i'd like to be able to tell the user the usage of the !foo command.  Right now if a check fails, then the bot fails silently and my users have no idea what's going on.

The best workaround I can figure is to somehow catch it in the error delegate, and try and figure out what happened based on the generic exception, which is very much not ideal.

Perhaps checks could be paired with failure handlers that we can set.

**Comment by uwx** [comment]
If you just want to show usage when binding fails, you can use the CommandErrored event and look for an ArgumentException, then invoke the help command using sudo or by hand.

If you want specific type errors:

In 3.2, use the CommandErrored event and look for an ArgumentException. Not many details are provided, but the exception message might be enough for your needs.

In 4.0, because of overloads, information about the underlying binding process is not exposed (only "Could not find a suitable overload for the command"), and I'm not sure if it will be in the future. That does however seem like a reasonable feature request though.

**Comment by uwx** [comment]
I propose the creation of a CommandArgumentException object which uses an enum for comparing what caused the exception rather than relying on string equality, which is prone to break at any point.

For [ConvertArgument](https://github.com/DSharpPlus/DSharpPlus/blob/master/DSharpPlus.CommandsNext/CommandsNextExtension.cs#L796-L818), I propose including the Type object that the argument was being converted to (rather than just the type name), and the string value. Context is not necessary since it might break encapsulation.

The exception thrown here:
https://github.com/DSharpPlus/DSharpPlus/blob/8375b999e2250f5eac5428f5c344494144d4c752/DSharpPlus.CommandsNext/Entities/Command.cs#L109
should include a Dictionary mapping CommandOverload => Exception that caused it to fail.

The current ChecksFailedException is fine.

cc @Emzi0767

**Comment by ellisonch** [comment]
I think I agree with uwx that perhaps all that needs to be figured out is a consistent way for CommandsNext to communicate the error to the programmer.  Right now, it triggers an event surrounding some kind of Exception object.  Some custom exceptions are used (e.g., CommandNotFoundException) but also some unspecific exceptions (e.g., ArgumentException when the end user passes a string to an int argument).

Ideally the way to handle this won't involve the programmer setting up a switch statement based on which type of Exception gets bubbled up.  This is why i suggested tying the handler to the event; if there's a cooldown violation, the cooldown violation event should be triggered.  If there's a check violation, the check violation event should be triggered

Perhaps this is tangential, but I can't help but think throwing exceptions is a weird way of handling these behaviors.  These aren't really exceptional events; they're totally normal, expected modes of failure.  Having them trigger events seems nice, but it doesn't need to be coupled with exceptions.  E.g., https://ericlippert.com/2008/09/10/vexing-exceptions/

**Comment by Emzi0767** [comment]
This is not a thing that will end up happening because check failure is a check failure - I won't implement an event per check, period. Furthermore, if we were to have an event per check, what about custom checks?

**Comment by uwx** [comment]
I think individual events would be an anti-pattern.

Ideally all you want to do when a command doesn't do what you expect it to is to display a neat message for the user, regardless of how critical the error is, so a switch statement is easier to maintain, and avoids mass copy-paste.

The second problem, and possibly the most dangerous one, is future-proofing. You can include a default branch in your switch statement, but you can't include a "default" event (and even if you could, that would be a terrible idea, since it still introduces logic that you can't be certain about for the future). What if we decide to add a new event type, or change the logic for an existing one? With a default branch you  can simply print out the exception message and go about your merry way. With separate events there's a good chance the change could be completely 

Additionally, I normally dislike using exceptions for control flow, but we're not actually _catching_ them, just using them as a way of passing information which includes a stack trace, and I can't think of any other way of doing that that wouldn't be a hack.

**Comment by Emzi0767** [comment]
> We could then just call the base (your attribute check implementation) and send a message from there.

No. No. No. And, once again, no. Communication is not anywhere near the area of what a check should do. That's what the event handlers should be doing.

A check should be doing a simple validation. Nothing more.

The problem outlined in here stems from complete lack of knowledge about how event-driven programming and polymorphism work.

**Comment by DapperMickie** [comment]
As I said, It's probably not ideal, no need to insult people.

The real question here is how should we proceed when wanting to give a reason why people can't use the command?

Should we just on command errored, get the command, and run all the checks ourselves to find out which validation failed and send a message accordingly or something?

So instead of saying how our solutions are wrong and stupid, can you please give us an answer to how we SHOULD do it?

**Comment by Emzi0767** [comment]
The exception gives you all the details, including the failed checks and the execution context. It's all listed in the docs and provided examples.

Facts are not insults.

**Comment by DapperMickie** [comment]
As a reference for people that actually want the answer to this question:

The example Emzi is referring to: https://github.com/DSharpPlus/Example-Bots/blob/master/DSPlus.Examples.CSharp.Ex02/Program.cs
starting from line 194 

The api documentation Emzi is referring to:
- for the checks failed exception that has the list of all the failed checks
https://dsharpplus.emzi0767.com/api/DSharpPlus.CommandsNext.Exceptions.ChecksFailedException.html
- for the CommandErrorEventArgs that is used in the example https://dsharpplus.emzi0767.com/api/DSharpPlus.CommandsNext.CommandErrorEventArgs.html

You might want to look at CommandEventArgs as well (because the CommandErrorEventArgs inherits this class).
So you'll have access to the command context (to send the message) and the list of all the failed checks.

Hopefully this will help some people!

oh and btw, making assumptions is not stating facts (even though he's right about me not reading every single line of all the examples).

**Comment by Emzi0767** [comment]
I recommend using nightly docs:
- https://dsharpplus.github.io/api/DSharpPlus.CommandsNext.Exceptions.ChecksFailedException.html
- https://dsharpplus.github.io/api/DSharpPlus.CommandsNext.CommandErrorEventArgs.html

I'm not going to comment on the assumptions beyond stating they're very reasonable given the question and resources available.

**Comment by DapperMickie** [comment]
Thanks for providing the correct links.
I'm looking forward to what this project brings us in the future.
Small suggestion, maybe we can have articles about the examples on the docs site, to keep all resources together.

And as reasonable as they might be, they were wrong (except for the examples part maybe).

**Comment by Neuheit** [comment]
>  Small suggestion, maybe we can have articles about the examples on the docs site, to keep all resources together.

We're doing a major cleanup of the doc articles for 4.0 in #629, so feel free to post your doc suggestions there.
