### ISSUE TITLE
GuildConnection#Channel can be null after connect

### ISSUE THREAD

**Issue by Kriste00** [DSharpPlus/DSharpPlus#359]
# Details
If the bot is not connected to any channel, then connects to one. Then when connecting to another one, The guild connection returned has its channel property set to null.

Root cause of #320 

Also the channel passed to the guild connection is never used:
https://github.com/DSharpPlus/DSharpPlus/blob/2ab9269b1817ea2d2bd3867b3fa23b540b3ef3dc/DSharpPlus.Lavalink/LavalinkGuildConnection.cs#L86-L98

# Fix
Maybe set the `Channel` property to the value passed in the constructor as the initial value.

# Steps to reproduce
1. Join a channel
2. Disconnect from the channel
3. Connect to a new channel

Bug: GuildConnection#Channel is null

<img width="392" alt="chnnull1" src="https://user-images.githubusercontent.com/32580874/45367167-f2773300-b5e0-11e8-9268-bd636091b852.PNG">
<img width="520" alt="chnnull2" src="https://user-images.githubusercontent.com/32580874/45367166-f2773300-b5e0-11e8-86f0-7ccd5e9bd156.PNG">
<img width="480" alt="chnnull3" src="https://user-images.githubusercontent.com/32580874/45367168-f2773300-b5e0-11e8-82e6-00a1198f85db.PNG">

**Comment by Emzi0767** [comment]
The old object doesn't lose its properties because it's not reused, it's gonna be disposed - this is nothing anomalous.

Since you're disconnecting and reconnecting in rapid succession you might be experiencing a race condition where the first voice state update received by the library is the one which assigns the bot a null channel. However as soon as the other voice state update is processed, the channel should be set to a correct value; what might be wrong is the session ID.

**Comment by Emzi0767** [comment]
Fixed by 883e2e8525ce8ea14bcd413f8283d551f1eb1729.
