### ISSUE TITLE
DSharpPlus Nightly builds from 00635 onward fail to locate opus.dll for VoiceNext no matter what on Win10

### ISSUE THREAD

**Issue by XanTheDragon** [DSharpPlus/DSharpPlus#499]
I did not have this issue on Windows 7, oddly. Upon moving to Windows 10 recently I had noticed that my bot's music system is failing entirely. This was tested on 00635 and I upgraded to 00640 just a moment ago.

The setup of my bot's executables contains the bot exe, all necessary DSharpPlus DLLs, `opus.dll`, and `sodium.dll`. On Windows 7 this setup worked fine, but on Windows 10, it is constantly giving me this error, despite opus.dll being next to the exe:

```
[16:55:08] [System.DllNotFoundException Thrown!] Unable to load DLL 'opus': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at DSharpPlus.VoiceNext.Codec.Interop._OpusCreateEncoder(Int32 sampleRate, Int32 channels, Int32 application, OpusError& error)
   at DSharpPlus.VoiceNext.Codec.Interop.OpusCreateEncoder(AudioFormat audioFormat)
   at DSharpPlus.VoiceNext.Codec.Opus..ctor(AudioFormat audioFormat)
   at DSharpPlus.VoiceNext.VoiceNextConnection..ctor(DiscordClient client, DiscordGuild guild, DiscordChannel channel, VoiceNextConfiguration config, VoiceServerUpdatePayload server, VoiceStateUpdatePayload state)
   at DSharpPlus.VoiceNext.VoiceNextExtension.<ConnectAsync>d__21.MoveNext()
```

**Comment by WamWooWam** [comment]
If you reinstalled Windows, it's very possible you're missing required MSVC runtimes. I'd need to ask @Emzi0767 to verify which you need, if any, but I'd start by downloading the 2017 MSVC++ runtime redistributables from [here](https://support.microsoft.com/en-ie/help/2977003/the-latest-supported-visual-c-downloads).

**Comment by uwx** [comment]
Way too many people struggle with this. I'm gonna try to clear everything up for the final time here.

Typically, DllImport goes in this order:

- The directory where `DSharpPlus.VoiceNext.dll` is located. For most builds this is the same directory as your bot's assembly, however depending on how it's executed it could, for instance, be located in the package directory (as referenced in deps.json, see [this explanation](https://natemcmaster.com/blog/2017/12/21/netcore-primitives/)). This depends on the .NET runtime version and how you run the program.
- The System32 directory, I.E. `%WinDir%\System32`. (You can delete this directory to make assembly resolution happen faster)

(Ref: [dotnet/buildtools#Microsoft.DotNet.Build.Tasks/PackageFiles/GenerateAssemblyInfo.Sdk.targets](
https://github.com/dotnet/buildtools/blob/7f4a8c88f526bf48c24d19414ac101f38ea35196/src/Microsoft.DotNet.Build.Tasks/PackageFiles/GenerateAssemblyInfo.Sdk.targets#L52))

This can be customized if we use [DefaultDllImportSearchPathsAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.defaultdllimportsearchpathsattribute.-ctor?view=netframework-4.8). I must stress however though that the attribute only applies if it's added to _the assembly importing the DLL itself_ (`DSharpPlus.VoiceNext.dll`), and it is _not_ under your control.

Did you notice something special here? If there is a deps.json file in your build directory, aka VoiceNext is loaded as a dependency from NuGet, putting an `opus.dll` file there would do... absolutely nothing. Conversely, if you use `dotnet publish`, the build directory will contain the VoiceNext dll, and you'll be able to put your opus.dll file there, and it'll get recognized.

So, why does this work on Windows 7 but not 10? My guess is either

- You're not running the bot the same way on both systems, so the way you run it on Windows 7 has the VoiceNext DLL in the same place as `opus.dll` and `sodium.dll`
- Windows 7 might use `DllImportSearchPath.LegacyBehavior` which, boo-fucking-hoo, searches _the application directory_, and you probably put the DLL in the bot's working directory when you run it on Win7.

Additionally, in 3.2 and before, the DllImport file names used are `libopus.dll` and `libsodium.dll`. In 4.x, the DllImport file names used are `opus.dll` and `sodium.dll`. This was added because Linux .NET Core can, by itself, resolve `lib*` names for libraries by just providing the name part. Since the prebuilt binary downloads are basically only for 3.2, they still have that name. Thus why, for a million times, we have to tell people to rename their DLLs.

So, how do we solve this fucking UX nightmare? Well, here are some options:

- Provide the natives as a NuGet package that puts them in the right place
- Use `[DefaultDllImportSearchPaths(DllImportSearchPath.ApplicationDirectory | DllImportSearchPath.AssemblyDirectory | DllImportSearchPath.System32)]` and tell people to put the DLLs in wherever the fuck the working directory is
- Use `[DefaultDllImportSearchPaths(DllImportSearchPath.UserDirectories | DllImportSearchPath.AssemblyDirectory | DllImportSearchPath.System32)]` and tell people to put the DLLs in `%PATH%` or point that variable to wherever the DLLs are

Note that only options 1 and 2 are compatible with legacy behavior.

**Comment by uwx** [comment]
And no, this doesn't have jack shit to do with MSVC runtimes. It uses [LoadLibraryEx]9https://docs.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-loadlibraryexa?redirectedfrom=MSDN).

**Comment by Emzi0767** [comment]
@WamWooWam the binaries are compiled statically, so there's no need to have msvc runtime installed.

@uwx the thought of providing them as a native package was actually the way I wanted to distribute them initially, but making native packages is a complicated process.

**Comment by XanTheDragon** [comment]
Feeling particularly aggressive today I see.. Ah well -- If it's of any assurance, I at least did what I could to resolve the issue myself. 

* I attempted to name them both `opus.dll` and `libopus.dll` since I did recall something in relation to changing the name. My mind filled in the blanks saying "It was to remove `lib`" since that's the setup I had and it's the setup that worked.
* After dealing with the program being unable to find these for some time with both names, I attempted to slap the DLLs into System32 for shits giggles because I know loading DLLs always goes there. Was completely out of ideas at this point. Program still couldn't find it.

My mistake for not mentioning this in my OP.

The only thing that I hadn't tried was using the `DefaultDllImportSearchPaths` attribute on my assembly, as I was unaware of the differing behavior from Win7 to Win10. Unfortunately for me, appending this to my assembly isn't helping at all.

With this information in mind -- anything new?

**Comment by uwx** [comment]
Have you tried putting the opus and sodium DLLs, naming as `opus.dll` and `sodium.dll`, into either the folder specified for the VoiceNext package in deps.json in your build folder, or in the build folder after using `dotnet publish`? And like I stated, DefaultDllImportSearchPaths will do nothing - it is _not_ under your control, it depends on the VoiceNext assembly itself having it.

In addition, the search will only go to `%windir%\System32` on 64-bit applications. Try adding the DLL to the `SysWOW64` folder instead.

**Comment by uwx** [comment]
Bonus: If you're still miserable or can't do all of this, you can try using AddDllDirectory.
```cs
[DllImport("kernel32.dll", SetLastError = true)]
static extern bool AddDllDirectory(string path);
```
I didn't suggest this earlier because it forces a Windows dependency.

**Comment by XanTheDragon** [comment]
I see.

I had initially skipped the method with deps.json since it flat out doesn't exist (I can't say I'm entirely certain as to why, unfortunately, given that I did use NuGet to grab the packages). Additionally, using `dotnet publish` didn't want to work out for me. I finally tried the `AddDllDirectory` extern, but it failed as well. As a last resort I ended up throwing the DLLs into SysWOW64 as well, but unfortunately, it *still* failed to find them, I can't say I'm certain as to what might be preventing it from finding the DLLs at this point.

**Comment by uwx** [comment]
.........Maybe install VC++ redistributables?

**Comment by XanTheDragon** [comment]
Nope. Already had those on hand.

**Comment by MichalPetryka** [comment]
Load it into Dependency Walker and see what it says.
http://www.dependencywalker.com/

**Comment by XanTheDragon** [comment]
I was going to redownload but https://dsharpplus.github.io/natives/index.html points to dead links. Could this be resolved?

**Comment by Kiritsu** [comment]
replace github.io with emzi0767.com

**Comment by Naamloos** [comment]
update?

**Comment by shroomzzz** [comment]
still an issue for me as well. have copied both DLLs to every location named above and still no dice even on latest nightly

**Comment by XanTheDragon** [comment]
I ended up building DSharpPlus.VoiceNext myself (By incorporating it's csproj file into my own bot) and I got it to work without problems.

**Comment by Emzi0767** [comment]
This issue is resolved with the introduction of the [natives package](https://www.nuget.org/packages/DSharpPlus.VoiceNext.Natives/).
