### ISSUE TITLE
[Suggestion] Migrate extension methods for separated namespace.

### ISSUE THREAD

**Issue by nathan130200** [DSharpPlus/DSharpPlus#964]
Since DSharpPlus can grow with builtin extensions. Instead of adding lot of namespace maybe consider moving all extension methods to separated namespace `DSharpPlus.Extensions`

For example in D#+ CNext, i just import D#+.CommandsNext then works. `UseCommandsNext` is ready for use. But D#+ Interactivity must add `DSharpPlus.Interactivity` and add extra line `DSharpPlus.Interactivity.Extensions` or at least make all interactivity extension methods in `DSharpPlus.Interactivity` namespace to avoid complexity.

Note: I didn't make an PR since idk, if this will be considered, and my time will get lost.

**Comment by VelvetThePanda** [comment]
Shoving 3 semi-unrelated namespaces under one umbrella is not a good idea. It makes the namespace vague and ambiguous, and doesn't tell you what features are added via importing that namespace. `DSharpPlus.CommandsNext` is a command frameowk, `DSharpPlus.Interactivity` is an interactivity package, and `DSharpPlus.Interactivity.Extensions` are various extension methods (from interactivity) for specific entities. It's verbose, and that's by design.

**Comment by nathan130200** [comment]
Ok, but we cannot see directly the extension methods, only when invoke that respective classes, so does not make sence separating these namespaces.

**Comment by VelvetThePanda** [comment]
What.

**Comment by VelvetThePanda** [comment]
Linq is exclusively extension methods, where as interactivity has direct *and* extension methods, hence why the namespace is splt. It's just decent architectural design.

**Comment by nathan130200** [comment]
I'm talking about `ClientExtensions`  class for interactivity, no necessity in `Extensions` sub-namespace

**Comment by uwx** [comment]
No, the purpose of extensions is to keep them separate. This also takes inspiration from [ASP.NET extension method conventions](https://docs.microsoft.com/en-us/dotnet/core/extensions/options-library-authors#namespace-guidance).
